package]
name = “ai_assistant”
version = "0.1.0"
edition = "2018"

# This project is a library
[lib]
name = “ai_assistant”
path = "src/lib.rs"
edition = "2018"

# Dependencies
[dependencies]
rsa = "0.4.0"
hex = "0.4"
ic-cdk = "0.8.0"
internet_identity = "0.1.0"
